version: '3'
services:
    frontend:
        build:
            context: ./frontend
        container_name: go_frontend
        restart: unless-stopped
        environment:
            CHOKIDAR_USEPOLLING: 'true'
            NODE_ENV: 'development'
        volumes:
            - './frontend:/code'
            - './logs/frontend:/root/.npm/_logs/'
        command: 'sh run_server.sh'
        ports:
            - '8080:3000'
        links:
            - backend
        depends_on:
            - backend
    backend:
        build:
            context: ./backend
        container_name: go_backend
        restart: unless-stopped
        environment:
            CHOKIDAR_USEPOLLING: 'true'
        volumes:
            - './backend:/code'
            - './logs/backend:/root/.npm/_logs/'
        command: 'sh run_server.sh'
        ports:
            - '8081:3000'
